/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'angel' at '8/4/15 7:52 PM' with Gradle 2.4
 *
 * @author angel, @date 8/4/15 7:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
